name: Quasiqueue Version Updater

# Every 30 minutes check for a new version of the package.
on:
  push:
    branches:
      - "main"
    # Don't self-trigger
    paths-ignore:
      - "**/README.md"
      - ".github/workflows/image-build.yml"
  schedule:
    - cron: "0,30 * * * *"

jobs:
  Version-Updater:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}

      - name: "Update Builder"
        uses: multi-py/action-python-versionator@main
        with:
          package: "quasiqueue"
          git_name: "Robert Hafner"
          git_email: "tedivm@tedivm.com"
          action_path: ${{ github.workspace }}/.github/workflows/image-build.yml
          update_python: false
